# NumPy

Źródła: 
Jake VanderPlas, Python Data Science Handbook, ESSENTIAL TOOLS FOR WORKING WITH DATA
Maciej Wilamowski, Łukasz Nawaro

Numpy to podstawowy pakiet Python'a służący do obsługi operacji macierzowych i wektorowych. Jest szybki, elastyczny, przydatny do obsługi dużych zbiorów danych i liczb pseudolosowych. Stanowi podstawę dla wielu innych pakietów (w tym Pandas). 

In [1]:
import numpy as np ### wczytujemy pakiet

### Array

array: lista zawierająca tylko jeden typ danych - bardziej wydajna forma danych (zajmuje mniej pamięci)

In [4]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

możemy też stworzyć macierz

In [3]:
np.array( [[1,1],[0,1]] )

array([[1, 1],
       [0, 1]])

In [2]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones((3, 5), dtype=float)

In [5]:
np.arange(0, 20, 2) ##podobny do range()

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [7]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [8]:
x1 = np.array([range(i, i + 3) for i in [2, 4, 6]])
x1

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [9]:
print("x1 ndim: ", x1.ndim)
print("x1 shape:", x1.shape)
print("x1 size: ", x1.size)
print("dtype:", x1.dtype)

x1 ndim:  2
x1 shape: (3, 3)
x1 size:  9
dtype: int64


### Zadanie

1. Stwórz array od 2 do 10
2. Stwórz macierz 4X6 z 0

In [12]:
np.arange(2,11)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

### Macierz z istniejącego obiektu
Czasem możemy chcieć utworzyć macierz z już istniejącego obiektu. W tym miejscu warto wspomnieć o tym, że zmiana kształtu macierzy jest łatwym i szybkim zadaniem nawet dla dużych macierzy. Nie zmienia to sposobu w jaki zapisana jest macierz w pamięci, ale jedynie sposób interpretacji pamięci.

In [15]:
x = list(range(12))
print("Lista: ", x)
print("Macierz numpy:", np.asarray(x))
print("Macierz numpy z nowym kształtem:\n", np.asarray(x).reshape((3, 4))) #krotka jako argument

Lista:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
Macierz numpy: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Macierz numpy z nowym kształtem:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Wektor/macierz jako range
Metoda reshape zastosowana na istniejącej macierzy nie zwróci jej kopii. Utworzy nowy "widok" tych samych danych. 

Prześledźmy poniższy przykład, poznając przy okazji sposób tworzenie macierzy z zakresu (arange), który przyjmuje analogiczne argumenty do pythonowego range.

In [16]:
r = np.arange(0, 23, 2)
print(r)
R = r.reshape((3, 4)) #Do R prypisz nowy widok z reshapowanego r
# Powyższą linię możemy alternatywnie napisać w ten sposób: R = reshape(r, (3, 4))

[ 0  2  4  6  8 10 12 14 16 18 20 22]


In [17]:
print(R)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [18]:
r[0]=10

In [19]:
print("Zmieniając zawartość 'r' zmienia się również zawartość 'R'") #kolumny i wierszy liczymy od 0
print(r)
print(R)


Zmieniając zawartość 'r' zmienia się również zawartość 'R'
[10  2  4  6  8 10 12 14 16 18 20 22]
[[10  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [20]:
x = np.array([1, 2, 3])
print(x)


[1 2 3]


In [21]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

### Zadanie

1. Stwórz 8 elementowy array od 1 do 8 i nazwaj go ar
2. Stwórz macierz 2X4 z ar 

In [22]:
ar = np.arange(1,9)
ar.reshape((2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Liczby losowe

In [23]:
print("Pojedyncze liczby losowe:")
print(np.random.random()) # float U~[0,1)] #z rzeczy random daj mi operacja losowa
print(np.random.randint(40, 50, size=6))
print(np.random.normal()) # float N~[0,1)]
print(np.random.normal(20, 5)) # float N~[20,5)]


print("\nMacierz z rozkładu jednostajnego [0,1):")
print(np.random.random((3, 4))) # float U~[0,1)]
print("\nMacierz z rozkładu normalnego N~(0,1):")
print(np.random.normal(size=(3, 4))) # float N~(0,1)]
print("\nMacierz z rozkładu normalnego N~(20,5):")
print(np.random.normal(20, 5, size=(3, 4))) # float N~(20,5)]

Pojedyncze liczby losowe:
0.30425966773599133
[41 43 47 43 40 45]
-0.8244871079756815
19.74638593281539

Macierz z rozkładu jednostajnego [0,1):
[[0.71257072 0.40009687 0.95220383 0.63030634]
 [0.81034869 0.40724065 0.8223803  0.81967286]
 [0.70680656 0.70979916 0.81053581 0.39065727]]

Macierz z rozkładu normalnego N~(0,1):
[[ 0.36802151 -1.23867455  1.53850894 -0.39585688]
 [ 0.04050972  1.08626067 -0.97604389  1.43904698]
 [-0.20480811 -0.94198497 -0.30114992 -1.13500748]]

Macierz z rozkładu normalnego N~(20,5):
[[27.56277026 11.8396092  22.47057159 21.69987298]
 [10.99766659 15.22625642 20.04834036 11.54287226]
 [21.49502317 24.8781553  24.46397978 17.86443468]]


In [ ]:
print(np.random.random())

### Zadanie

1. Wylosuj pojedynczą liczbę z rozkladu  N~[40,6)]
2. Wylosuj macierz 4X6 z rozkladu  N~[40,6)]

### Adresowanie i indeksowanie
Numpy domyślnie tworzy macierze w układzie wierszowym. Kiedy z dwuwymiarowej macierzy wybierzemy fragment stosując tylko jeden wymiar, uzyskamy stosowny wiersz. Jeżeli chcemy wybrać kolumnę musimy wybrać też wszystkie wiersze (:). 

In [ ]:
r = np.arange(0, 12)
r.shape=(3, 4)
print(r)
print("Wiersz: ", r[2], "ma wymiar", r[2].shape) # alternatywnie, r[2, :]
print("Kolumna: ", r[:,2])

In [ ]:
x1 = np.random.randint(10, size=6)

In [ ]:
print(x1)

In [ ]:
x1[-1]

In [ ]:
x1[:5]

In [ ]:
x1[::2]

In [ ]:
x2 = np.random.randint(10, size=(3, 4))

In [ ]:
x2

In [ ]:
x2[0, 0]

In [ ]:
x2[2, -1]

In [ ]:
x2[:2, :3] ##rows, columns

In [ ]:
x2[0, :] # first row of x2

In [ ]:
print(x2[:, 0]) # first column of x2

### Łączenie/dzielenie macierzy
To często wykonywane operacja. Przydatne tutaj funkcje to concatenate i split. Pierwszą z tych nazw trudno zapamiętać, jeżeli ktoś woli może korzystać z aliasów w postaci vstack i hstack. 


In [24]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1]) 
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [25]:
z = [99, 99, 99]

np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [26]:
grid = np.array([[1, 2, 3],[4, 5, 6]])

In [27]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
np.concatenate([grid, grid]) 

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [29]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [30]:
np.concatenate([grid, grid], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

https://www.sharpsightlabs.com/blog/numpy-axes-explained/

In [31]:
x = np.array([1, 2, 3])

Różne rozmiary: vertical stack oraz horizontal stack

In [32]:
grid = np.array([[9, 8, 7],[6, 5, 4]])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [33]:
y = np.array([[99],[99]])

In [34]:
y

array([[99],
       [99]])

In [35]:
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [36]:
x = np.random.randint(0, 12, size=(3, 4))
y = np.random.randint(0, 12, size=(3, 4))
print(x.shape, y.shape)
print(x)
print(y)
print("Sklejanie w pionie:")
print(np.concatenate((x,y), axis=0))
#print(np.vstack((x,y)))
print(np.concatenate((x,y), axis=0).shape, np.vstack((x,y)).shape)
print("Sklejanie w poziomie:")
print(np.hstack((x,y)))
print(np.concatenate((x,y), axis=1).shape, np.hstack((x,y)).shape)


(3, 4) (3, 4)
[[2 5 0 2]
 [4 0 1 9]
 [3 4 9 7]]
[[8 2 2 3]
 [1 9 4 6]
 [4 1 7 3]]
Sklejanie w pionie:
[[2 5 0 2]
 [4 0 1 9]
 [3 4 9 7]
 [8 2 2 3]
 [1 9 4 6]
 [4 1 7 3]]
(6, 4) (6, 4)
Sklejanie w poziomie:
[[2 5 0 2 8 2 2 3]
 [4 0 1 9 1 9 4 6]
 [3 4 9 7 4 1 7 3]]
(3, 8) (3, 8)


Split zwróci nam listę

In [37]:
x = [1, 2, 3, 99, 99, 3, 2, 1]

x1, x2, x3 = np.split(x, [3, 5])

print(x1, x2, x3)

print(x[:3], x[3:5], x[5:])


[1 2 3] [99 99] [3 2 1]
[1, 2, 3] [99, 99] [3, 2, 1]


In [ ]:
x = np.random.randint(0, 12, size=(3, 4))
print(x)
print(np.split(x, 3, axis=0))
print(np.split(x, 4, axis=1))


### Zadanie
1. Stwórz 2 macierze 2X3 z random liczbami między 10 a 20,  połącz je wertykalnie oraz horyzontalnie

## Algebra i inne funkcje.
Numpy posiada wiele wbudowanych funkcji matematycznych, algebraicznych i innych. Poniżej ograniczmy się do zaledwie kilku przykładów. Najważniejsze jest sprawne odszukiwanie funkcji w dokumentacji. Dzięki temu nie tylko dowiemy się czy funkcja jest zaimplementowana, ale również możemy szybko sprawdzić sposób jej implementacji.

Poniżej na przykładzie funkcji matematycznych zobaczymy jak ważne jest korzystanie z wbudowanych funkcji, kiedy to tylko możliwe.

* Funkcje matematyczne: https://docs.scipy.org/doc/numpy/reference/routines.math.html
* Funkcje algebraiczne: https://docs.scipy.org/doc/numpy/reference/routines.linalg.html
* Funkcje statystyczne: https://numpy.org/doc/stable/reference/routines.statistics.html
* Wykaz pozostałych grup funkcji: https://docs.scipy.org/doc/numpy/reference/index.html

In [ ]:
x = np.arange(4)

print("x =", x)
print("x + 5 =", x + 5) 
print("x - 5 =", x - 5) 
print("x * 2 =", x * 2)
print("x / 2 =", x / 2) 
print("x // 2 =", x // 2)

In [ ]:
x = np.array([-2, -1, 0, 1, 2])

abs(x)

In [ ]:
np.absolute(x)

In [ ]:
x=[1, 2, 3]
print(np.exp(x))
print(np.exp2(x))
print(np.power(3, x))

In [ ]:
import math
x = np.random.normal(size=(10000, 1))
print("Max:")
%timeit -n 100 max(x)
%timeit -n 100 x.max()

print("Sin:")
%timeit -n 100 [math.sin(z) for z in x]
%timeit -n 100 np.sin(x)

print("Mean:")
%timeit -n 100 np.mean(x)
%timeit -n 100 x.mean()

In [ ]:
M = np.arange(0, 4)
N = np.arange(1, 5)
print(M)
print(N)
print("Mnożenie wektorów:")
print(np.dot(M,N))

print("\nDla macierzy")
M = np.arange(0, 4)
N = np.arange(1, 5)
M.shape=(2, 2)
N.shape=(2, 2)
print(M)
print(N)
print("\nMnożenie macierzy:")
print(np.dot(M,N))
print("\nOdwracanie macierzy:")
print(np.linalg.inv(M))